version: '3'

services:
  tomcat:
    build:
      context: .
      dockerfile: Dockerfile
	  container_name: tomcat
	  ports: 
		- "80:80"
	  volumes:
      - logs:tomcat-app/logs
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    depends_on:
      - tomcat
    
